data: criteo_x4
data_root: ../data/criteo_all
raw_data: raw_data
tfr_data: tfr_data
output_feature: feature_data
tfr_data_size: 1000000
data_format: csv
train_data: train.tiny.csv
test_data: test.tiny.csv
valid_data: valid.tiny.csv
feature_cols:
  - {name: [I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13],
     dtype: float, type: categorical, preprocess: convert_to_bucket, na_value: 0}
  - {name: [C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26],
     dtype: string, type: categorical, na_value: "", min_count: 10}
label_col: {name: Label, dtype: float}