# default config
workers: 3 # not use
verbose: 1
shuffle_factor: 1000
early_stopping: {monitor: val_auc, mode: 'max', patience: 10, verbose: 1,
                 min_delta: 0.001, baseline: 0.0, restore_best_weights: False}
checkpoint: {filepath: ../data/criteo_all/checkpoint, monitor: val_auc, verbose: 1, save_best_only: True,
             save_weights_only: False, mode: 'max', save_freq: epoch}
tensorboard: {log_dir: '../data/criteo_all/logs', histogram_freq: 0, batch_size: 32, write_graph: True,
               write_grads: False, write_images: False, embeddings_freq: 0, embeddings_layer_names: None,
               embeddings_metadata: None, embeddings_data: None, update_freq: 'epoch'}

# model config
model: LR
loss: binary_crossentropy
metrics: [accuracy, AUC]
task: binary_classification
optimizer: adam
learning_rate: 1.0e-3
regularizer: 0
batch_size: 100000
epochs: 100
embed_dim: 1
seed: 20190601
monitor: val_auc